# Generated by Django 5.0.4 on 2024-05-06 10:55

import django.db.models.deletion
import mptt.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_furniture_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='child', to='items.furniture'),
        ),
    ]
