# Generated by Django 5.0.4 on 2024-05-08 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_furniture_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='furniture',
            name='parent',
        ),
    ]
